### ISSUE TITLE
Transaction Time Out, Not being able to mint 

### ISSUE THREAD

**Issue by GodMaiden** [Fulgurus/candy-machine-v2-responsive-ui#27]
I'm trying the create a collection on solana,
The whole process from creating wallet and working 
with metaplex was super smooth and worked perfectly,
Copied my CM address to The env folder, and installed all the dependencies, when I use yarn start everything seems fine the the host opens and connects my wallet, when I click mint the transaction sign says transaction might fail and after I sign it I get "Transaction time out"
My wallet has balance tho, and when I checked the tr id, the problem was at #5 instruction, any help please?

**Comment by GodMaiden** [comment]
and when I type the command:
 ts-node C:\Users\xxxx\Desktop\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts mint_one_token -e devnet -k C:/Users/xxxx/Desktop/~/.config/solana/devnet.json -cp C:\Users\xxxx\Desktop\~\metaplex\js\packages\cli\example-candy-machine-upload-config.json C:\Users\xxxx\Desktop\~\metaplex\assets
I get this:
 const candyMachine = new PublicKey(cacheContent.program.candyMachine);       
                                                    ^
TypeError: Cannot read properties of undefined (reading 'program')
    at Command.<anonymous> (C:\Users\alimr\Desktop\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:991:53)
    at Command.listener [as _actionHandler] (C:\Users\alimr\Desktop\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:480:17)
    at C:\Users\alimr\Desktop\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1234:65
    at Command._chainOrCall (C:\Users\alimr\Desktop\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1151:12)
    at Command._parseCommand (C:\Users\alimr\Desktop\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1234:27)
    at Command._dispatchSubcommand (C:\Users\alimr\Desktop\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1057:25)    
    at Command._parseCommand (C:\Users\alimr\Desktop\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1200:19)
    at Command.parse (C:\Users\alimr\Desktop\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:889:10)
    at Object.<anonymous> (C:\Users\alimr\Desktop\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:1258:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

**Comment by Fulgurus** [comment]
It looks like you didn't specify .env variables properly. Check the followings :
- did you rename your .env.sample to .env file ?
- did you set the three required variables : REACT_APP_CANDY_MACHINE_ID , REACT_APP_SOLANA_RPC_HOST , REACT_APP_SOLANA_NETWORK
- are you sell you well commited/pushed this .env file to your repository

**Comment by GodMaiden** [comment]
Yes I did change the name to .env and thats how it looks like:
REACT_APP_CANDY_MACHINE_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
REACT_APP_SOLANA_NETWORK=devnet
REACT_APP_SOLANA_RPC_HOST=https://api.devnet.solana.com


# ADDITIONAL PARAMS TO SET IF USING SPL-TOKEN AS MINTING CURRENCY ONLY :
# Spl-Token symbol to display next the price
REACT_APP_SPL_TOKEN_TO_MINT_NAME=

# Spl-token decimals place defined on creation (default is 9)
REACT_APP_SPL_TOKEN_TO_MINT_DECIMALS=

# To avoid harmless compilation warnings generating a build error, keep CI set to false
CI=false


I'm working on the devnet, and forgot to metion even tho the transaction fails I get an unkown token

**Comment by Fulgurus** [comment]
@GodMaiden can you confirm that the issue has been resolved on your side and was coming from your config.json file goLiveDate invalid ?
